server:
  address: http://f81e57c4.ngrok.io
  key: 1634abcb8d25c082c3ecbfd849c41065

client:
  platforms: all
  store_tasks: 10
  use_opencl: true
  heartbeat: 3
  storage_dir: ./storage
  loader_location: ./../engths2013/soft/build/mtx_loader

