server:
  address: https://dnjbdxiklb.localtunnel.me
  key: 9caa4cba174e6a90f6ae99d798e72b6c
client:
  platforms: all
  min_tasks: 1
  platforms: all # unused for now
  store_tasks: 1
  use_opencl: true
  heartbeat: 30
